[package]
license = ["Apache-2.0"]
keywords = ["Commerce/eCommerce", "Cost/Paid", "Trigger"]
org = "ballerinax"
name = "trigger.shopify"
repository = "https://github.com/ballerina-platform/asyncapi-triggers"
version = "1.3.0"
distribution = "2201.4.1"
icon = "docs/icon.png"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
