[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Authentication", "Cost/Freemium"]
org = "ballerinax"
name = "trigger.asgardeo"
repository = "https://github.com/ballerina-platform/asyncapi-triggers"
version = "0.7.0"
distribution = "2201.8.0"
icon = "docs/icon.png"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "io.crypto"
artifactId = "decryption-native"
version = "0.0.6"
path = "../../native/asgardeo/build/libs/asgardeo-0.0.6.jar"
