[package]
license = ["Apache-2.0"]
keywords = ["Cost/Freemium", "Trigger"]
org = "ballerinax"
name = "trigger.google.mail"
repository = "https://github.com/ballerina-platform/asyncapi-triggers"
version = "0.8.0"
distribution = "2201.2.1"
icon = "docs/icon.png"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
