[package]
license = ["Apache-2.0"]
keywords = ["Finance/Accounting", "Cost/Paid", "Trigger"]
org = "ballerinax"
name = "trigger.quickbooks"
repository = "https://github.com/ballerina-platform/asyncapi-triggers"
version = "0.1.0"
distribution = "2201.1.1"
icon = "docs/icon.png"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true