[package]
license = ["Apache-2.0"]
keywords = ["Communication chat/voice", "Cost/Freemium" , "Vendor/Twilio"]
org = "ballerinax"
name = "trigger.twilio"
repository = "https://github.com/ballerina-platform/asyncapi-triggers"
version = "0.7.0"
icon = "docs/icon.png"
distribution = "2201.0.4"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
