[package]
license = ["Apache-2.0"]
keywords = ["Communication/Team Chat", "Cost/Freemium"]
org = "ballerinax"
name = "trigger.slack"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/asyncapi-triggers"
version = "0.6.3"
distribution = "slbeta6"
icon = "docs/icon.png"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
